name: mysam_myplan
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1    # For authentication
  cloud_firestore: ^5.4.4   # For Firestore database
  firebase_messaging: ^15.1.3 # For push notifications
  flutter_local_notifications: ^18.0.1 # For local reminders
  syncfusion_flutter_calendar: ^20.4.0
  syncfusion_flutter_core: ^20.4.0
  intl: ^0.19.0 
  dropdown_textfield: ^1.2.0
  timezone: ^0.9.1
  http: ^1.2.2
  flutter_colorpicker: ^1.0.3
  rrule: ^0.2.0
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/planny.png
    - assets/images/transparent_planny_1152_splash - Copy.png

